"""initial schema

Revision ID: 65c32b5e3f63
Revises:
Create Date: 2026-08-04 08:25:30.597034
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65c32b5e3f63"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("alert_key", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("decimal_odds", sa.Float(), nullable=False),
        sa.Column("ev", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("alert_key", "channel"),
    )
    op.create_table(
        "challenges",
        sa.Column("challenge_id", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("challenge_id"),
    )
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_challenges_state"), ["state"], unique=False)

    op.create_table(
        "events",
        sa.Column("canonical_id", sa.String(length=64), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column("competition", sa.String(length=160), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("surface", sa.String(length=32), nullable=True),
        sa.Column("sets_to_win", sa.Integer(), nullable=True),
        sa.Column("home_name", sa.String(length=160), nullable=False),
        sa.Column("away_name", sa.String(length=160), nullable=False),
        sa.Column("home_canonical_id", sa.String(length=160), nullable=False),
        sa.Column("away_canonical_id", sa.String(length=160), nullable=False),
        sa.Column("start_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mapping_ambiguous", sa.Boolean(), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("canonical_id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_away_canonical_id"), ["away_canonical_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_home_canonical_id"), ["home_canonical_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_sport"), ["sport"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_events_start_time_utc"), ["start_time_utc"], unique=False
        )

    op.create_table(
        "scan_runs",
        sa.Column("scan_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=32), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("rejection_count", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("scan_id"),
    )
    with op.batch_alter_table("scan_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_runs_config_fingerprint"), ["config_fingerprint"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_runs_generated_at"), ["generated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scan_runs_mode"), ["mode"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_runs_status"), ["status"], unique=False)

    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("scan_id", sa.String(length=32), nullable=False),
        sa.Column("alert_key", sa.String(length=32), nullable=False),
        sa.Column("event_canonical_id", sa.String(length=64), nullable=False),
        sa.Column("selection_key", sa.String(length=160), nullable=False),
        sa.Column("bookmaker", sa.String(length=64), nullable=False),
        sa.Column("decimal_odds", sa.Float(), nullable=False),
        sa.Column("model_probability", sa.Float(), nullable=False),
        sa.Column("ev", sa.Float(), nullable=False),
        sa.Column("ev_conservative", sa.Float(), nullable=False),
        sa.Column("data_quality", sa.Float(), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan_runs.scan_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.create_index("ix_candidate_scan", ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_candidates_alert_key"), ["alert_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_candidates_ev"), ["ev"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_candidates_event_canonical_id"), ["event_canonical_id"], unique=False
        )

    op.create_table(
        "challenge_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("challenge_id", sa.String(length=32), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.challenge_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenge_id", "step_index", name="uq_challenge_step"),
    )
    with op.batch_alter_table("challenge_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_challenge_steps_challenge_id"), ["challenge_id"], unique=False
        )

    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("bookmaker", sa.String(length=64), nullable=False),
        sa.Column("event_canonical_id", sa.String(length=64), nullable=False),
        sa.Column("event_source_id", sa.String(length=128), nullable=False),
        sa.Column("selection_key", sa.String(length=160), nullable=False),
        sa.Column("market", sa.String(length=48), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("line", sa.Float(), nullable=True),
        sa.Column("selection_code", sa.String(length=48), nullable=False),
        sa.Column("selection_label", sa.String(length=200), nullable=False),
        sa.Column("decimal_odds", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("event_status", sa.String(length=32), nullable=False),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_meta", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_canonical_id"],
            ["events.canonical_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_odds_fingerprint"),
    )
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_odds_event_selection", ["event_canonical_id", "selection_key"], unique=False
        )
        batch_op.create_index("ix_odds_observed_at", ["observed_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_odds_snapshots_bookmaker"), ["bookmaker"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_odds_snapshots_event_canonical_id"), ["event_canonical_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_odds_snapshots_provider"), ["provider"], unique=False)

    op.create_table(
        "rejections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.String(length=32), nullable=False),
        sa.Column("event_canonical_id", sa.String(length=64), nullable=False),
        sa.Column("event_label", sa.String(length=320), nullable=False),
        sa.Column("selection_key", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan_runs.scan_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rejections", schema=None) as batch_op:
        batch_op.create_index("ix_rejection_scan", ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rejections_code"), ["code"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rejections_event_canonical_id"), ["event_canonical_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rejections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rejections_event_canonical_id"))
        batch_op.drop_index(batch_op.f("ix_rejections_code"))
        batch_op.drop_index("ix_rejection_scan")

    op.drop_table("rejections")
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_odds_snapshots_provider"))
        batch_op.drop_index(batch_op.f("ix_odds_snapshots_event_canonical_id"))
        batch_op.drop_index(batch_op.f("ix_odds_snapshots_bookmaker"))
        batch_op.drop_index("ix_odds_observed_at")
        batch_op.drop_index("ix_odds_event_selection")

    op.drop_table("odds_snapshots")
    with op.batch_alter_table("challenge_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenge_steps_challenge_id"))

    op.drop_table("challenge_steps")
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidates_event_canonical_id"))
        batch_op.drop_index(batch_op.f("ix_candidates_ev"))
        batch_op.drop_index(batch_op.f("ix_candidates_alert_key"))
        batch_op.drop_index("ix_candidate_scan")

    op.drop_table("candidates")
    with op.batch_alter_table("scan_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_runs_status"))
        batch_op.drop_index(batch_op.f("ix_scan_runs_mode"))
        batch_op.drop_index(batch_op.f("ix_scan_runs_generated_at"))
        batch_op.drop_index(batch_op.f("ix_scan_runs_config_fingerprint"))

    op.drop_table("scan_runs")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_start_time_utc"))
        batch_op.drop_index(batch_op.f("ix_events_sport"))
        batch_op.drop_index(batch_op.f("ix_events_home_canonical_id"))
        batch_op.drop_index(batch_op.f("ix_events_away_canonical_id"))

    op.drop_table("events")
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenges_state"))

    op.drop_table("challenges")
    op.drop_table("alerts")
    # ### end Alembic commands ###
